openapi: 3.1.0
info:
  title: Content Authoring and Versioning - Notifications API
  version: 1.0.0
  description: API for managing in-app notifications for review and publication events

servers:
  - url: /api/v1
    description: API v1

tags:
  - name: Notifications
    description: In-app notification management

paths:
  /notifications:
    get:
      operationId: listNotifications
      summary: List user notifications
      description: Returns the authenticated user's notifications, ordered by creation date descending
      tags: [Notifications]
      security:
        - CookieAuth: []
        - BearerAuth: []
      parameters:
        - name: isRead
          in: query
          schema:
            type: boolean
          description: Filter by read/unread status
        - name: type
          in: query
          schema:
            type: string
            enum: [review_requested, review_completed, changes_requested, content_published]
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 20
      responses:
        '200':
          description: Notification list
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: array
                    items:
                      $ref: '#/components/schemas/Notification'
                  pagination:
                    $ref: '#/components/schemas/Pagination'
        '401':
          description: Not authenticated

  /notifications/unread-count:
    get:
      operationId: getUnreadCount
      summary: Get unread notification count
      description: Returns the count of unread notifications for the authenticated user
      tags: [Notifications]
      security:
        - CookieAuth: []
        - BearerAuth: []
      responses:
        '200':
          description: Unread count
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    type: object
                    properties:
                      count:
                        type: integer
        '401':
          description: Not authenticated

  /notifications/{notificationId}/read:
    patch:
      operationId: markNotificationRead
      summary: Mark notification as read
      description: Marks a single notification as read for the authenticated user
      tags: [Notifications]
      security:
        - CookieAuth: []
        - BearerAuth: []
      parameters:
        - name: notificationId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Notification marked as read
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/Notification'
        '404':
          description: Notification not found or not owned by user

components:
  securitySchemes:
    CookieAuth:
      type: apiKey
      in: cookie
      name: echo_session
    BearerAuth:
      type: http
      scheme: bearer

  schemas:
    Notification:
      type: object
      properties:
        id:
          type: string
          format: uuid
        type:
          type: string
          enum: [review_requested, review_completed, changes_requested, content_published]
        title:
          type: string
        message:
          type: string
        resourceType:
          type: string
          enum: [content, branch, review]
        resourceId:
          type: string
          format: uuid
        isRead:
          type: boolean
        createdAt:
          type: string
          format: date-time
        readAt:
          type: string
          format: date-time

    Pagination:
      type: object
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        hasMore:
          type: boolean
