openapi: 3.1.0
info:
  title: Echo Portal Audit API
  description: Audit log query and compliance endpoints
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /audit/logs:
    get:
      operationId: queryAuditLogs
      summary: Query audit logs
      description: Search and filter audit logs (admin only)
      tags:
        - Audit
      security:
        - sessionCookie: []
      parameters:
        - name: actorId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by actor who performed action
        - name: resourceId
          in: query
          schema:
            type: string
            format: uuid
          description: Filter by affected resource (branch, user, etc.)
        - name: resourceType
          in: query
          schema:
            type: string
            enum: [branch, user, review, session]
          description: Filter by resource type
        - name: action
          in: query
          schema:
            $ref: '#/components/schemas/AuditAction'
          description: Filter by action type
        - name: outcome
          in: query
          schema:
            type: string
            enum: [success, denied]
          description: Filter by outcome
        - name: startDate
          in: query
          schema:
            type: string
            format: date-time
          description: Start of time range (inclusive)
        - name: endDate
          in: query
          schema:
            type: string
            format: date-time
          description: End of time range (inclusive)
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
      responses:
        '200':
          description: Audit log entries
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogResponse'
        '403':
          description: Not authorized (requires administrator role)

  /audit/logs/{logId}:
    get:
      operationId: getAuditLogEntry
      summary: Get single audit log entry
      description: Returns detailed audit log entry
      tags:
        - Audit
      security:
        - sessionCookie: []
      parameters:
        - name: logId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Audit log entry detail
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogEntryDetail'
        '403':
          description: Not authorized
        '404':
          description: Entry not found

  /audit/branches/{branchId}:
    get:
      operationId: getBranchAuditHistory
      summary: Get branch audit history
      description: Returns all audit events for a specific branch
      tags:
        - Audit
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
      responses:
        '200':
          description: Branch audit history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogResponse'
        '403':
          description: Not authorized to view branch
        '404':
          description: Branch not found

  /audit/users/{userId}:
    get:
      operationId: getUserAuditHistory
      summary: Get user activity history
      description: Returns all audit events involving a specific user as actor
      tags:
        - Audit
      security:
        - sessionCookie: []
      parameters:
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: page
          in: query
          schema:
            type: integer
            default: 1
        - name: limit
          in: query
          schema:
            type: integer
            default: 50
            maximum: 200
      responses:
        '200':
          description: User activity history
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AuditLogResponse'
        '403':
          description: Not authorized (requires administrator)
        '404':
          description: User not found

  /audit/security/failed-logins:
    get:
      operationId: getFailedLoginReport
      summary: Get failed login attempts report
      description: Returns summary of failed authentication attempts
      tags:
        - Audit
        - Security
      security:
        - sessionCookie: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: groupBy
          in: query
          schema:
            type: string
            enum: [email, ip_address, hour, day]
            default: email
      responses:
        '200':
          description: Failed login report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FailedLoginReport'
        '403':
          description: Not authorized

  /audit/security/permission-denials:
    get:
      operationId: getPermissionDenialReport
      summary: Get permission denial report
      description: Returns summary of permission denial events
      tags:
        - Audit
        - Security
      security:
        - sessionCookie: []
      parameters:
        - name: startDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: endDate
          in: query
          required: true
          schema:
            type: string
            format: date-time
        - name: groupBy
          in: query
          schema:
            type: string
            enum: [actor, permission, resource_type]
            default: permission
      responses:
        '200':
          description: Permission denial report
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDenialReport'
        '403':
          description: Not authorized

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: echo_session

  schemas:
    AuditLogResponse:
      type: object
      required:
        - entries
        - pagination
      properties:
        entries:
          type: array
          items:
            $ref: '#/components/schemas/AuditLogEntry'
        pagination:
          $ref: '#/components/schemas/Pagination'

    AuditLogEntry:
      type: object
      required:
        - id
        - timestamp
        - actorId
        - action
        - resourceId
        - resourceType
        - outcome
      properties:
        id:
          type: string
          format: uuid
        timestamp:
          type: string
          format: date-time
        actorId:
          type: string
          format: uuid
        actorEmail:
          type: string
          format: email
        actorDisplayName:
          type: string
        action:
          $ref: '#/components/schemas/AuditAction'
        resourceId:
          type: string
          format: uuid
        resourceType:
          type: string
          enum: [branch, user, review, session]
        outcome:
          type: string
          enum: [success, denied]
        summary:
          type: string
          description: Human-readable summary of the action

    AuditLogEntryDetail:
      allOf:
        - $ref: '#/components/schemas/AuditLogEntry'
        - type: object
          properties:
            metadata:
              type: object
              description: Additional context (old/new values, reason, etc.)
              additionalProperties: true
            initiatingUserId:
              type: string
              format: uuid
              description: For AI-assisted actions, the human who initiated
            ipAddress:
              type: string
            userAgent:
              type: string

    AuditAction:
      type: string
      enum:
        - auth.login
        - auth.logout
        - auth.failed
        - auth.locked
        - auth.session_expired
        - role.changed
        - permission.granted
        - permission.denied
        - branch.created
        - branch.updated
        - branch.transitioned
        - branch.published
        - branch.archived
        - review.assigned
        - review.approved
        - review.rejected
        - review.changes_requested
        - collaborator.added
        - collaborator.removed
        - reviewer.assigned
        - reviewer.unassigned

    FailedLoginReport:
      type: object
      required:
        - startDate
        - endDate
        - totalAttempts
        - uniqueEmails
        - uniqueIPs
        - groupedData
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        totalAttempts:
          type: integer
        uniqueEmails:
          type: integer
        uniqueIPs:
          type: integer
        lockedAccounts:
          type: integer
        groupedData:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              count:
                type: integer
              lastAttempt:
                type: string
                format: date-time

    PermissionDenialReport:
      type: object
      required:
        - startDate
        - endDate
        - totalDenials
        - groupedData
      properties:
        startDate:
          type: string
          format: date-time
        endDate:
          type: string
          format: date-time
        totalDenials:
          type: integer
        uniqueActors:
          type: integer
        groupedData:
          type: array
          items:
            type: object
            properties:
              key:
                type: string
              count:
                type: integer
              actors:
                type: integer
                description: Unique actors denied this permission

    Pagination:
      type: object
      required:
        - page
        - limit
        - total
        - totalPages
      properties:
        page:
          type: integer
        limit:
          type: integer
        total:
          type: integer
        totalPages:
          type: integer
