openapi: 3.1.0
info:
  title: Echo Portal Permissions API
  description: Permission evaluation and access control endpoints
  version: 1.0.0

servers:
  - url: /api/v1
    description: API v1

paths:
  /permissions/check:
    post:
      operationId: checkPermission
      summary: Check if user has permission
      description: Evaluates permission in context of branch, state, and visibility
      tags:
        - Permissions
      security:
        - sessionCookie: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PermissionCheckRequest'
      responses:
        '200':
          description: Permission check result
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionCheckResponse'

  /permissions/my-permissions:
    get:
      operationId: getMyPermissions
      summary: Get current user's permissions
      description: Returns all permissions for the authenticated user
      tags:
        - Permissions
      security:
        - sessionCookie: []
      responses:
        '200':
          description: User's permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/UserPermissions'

  /branches/{branchId}/permissions:
    get:
      operationId: getBranchPermissions
      summary: Get permissions for a branch
      description: Returns the current user's permissions for a specific branch
      tags:
        - Permissions
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Branch-specific permissions
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BranchPermissions'
        '403':
          description: No access to branch
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PermissionDeniedError'
        '404':
          description: Branch not found

  /branches/{branchId}/collaborators:
    get:
      operationId: listCollaborators
      summary: List branch collaborators
      description: Returns users with collaboration access to the branch
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of collaborators
          content:
            application/json:
              schema:
                type: object
                properties:
                  collaborators:
                    type: array
                    items:
                      $ref: '#/components/schemas/CollaboratorSummary'

    post:
      operationId: addCollaborator
      summary: Add collaborator to branch
      description: Grants edit access to another user (branch owner only, draft state only)
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Collaborator added
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CollaboratorSummary'
        '400':
          description: Cannot add owner as collaborator or branch not in draft state
        '403':
          description: Not branch owner

  /branches/{branchId}/collaborators/{userId}:
    delete:
      operationId: removeCollaborator
      summary: Remove collaborator from branch
      description: Revokes edit access from a collaborator
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Collaborator removed
        '403':
          description: Not branch owner
        '404':
          description: Collaborator not found

  /branches/{branchId}/reviewers:
    get:
      operationId: listAssignedReviewers
      summary: List assigned reviewers
      description: Returns users assigned to review the branch
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: List of assigned reviewers
          content:
            application/json:
              schema:
                type: object
                properties:
                  reviewers:
                    type: array
                    items:
                      $ref: '#/components/schemas/ReviewerSummary'
                  requiredApprovals:
                    type: integer
                  currentApprovals:
                    type: integer

    post:
      operationId: assignReviewer
      summary: Assign reviewer to branch
      description: Assigns a user to review the branch (owner or admin only)
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - userId
              properties:
                userId:
                  type: string
                  format: uuid
      responses:
        '201':
          description: Reviewer assigned
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ReviewerSummary'
        '400':
          description: Cannot assign owner, collaborator, or non-reviewer role user
        '403':
          description: Not authorized to assign reviewers

  /branches/{branchId}/reviewers/{userId}:
    delete:
      operationId: unassignReviewer
      summary: Unassign reviewer from branch
      description: Removes reviewer assignment
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
        - name: userId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Reviewer unassigned
        '400':
          description: Cannot remove last reviewer while in review state
        '403':
          description: Not authorized

  /branches/{branchId}/approval-threshold:
    put:
      operationId: setApprovalThreshold
      summary: Set required approvals for branch
      description: Configure number of approvals needed (admin only)
      tags:
        - Branch Access
      security:
        - sessionCookie: []
      parameters:
        - name: branchId
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - requiredApprovals
              properties:
                requiredApprovals:
                  type: integer
                  minimum: 1
                  maximum: 10
      responses:
        '200':
          description: Threshold updated
          content:
            application/json:
              schema:
                type: object
                properties:
                  requiredApprovals:
                    type: integer
        '400':
          description: Threshold cannot exceed assigned reviewer count
        '403':
          description: Not authorized (requires administrator)

components:
  securitySchemes:
    sessionCookie:
      type: apiKey
      in: cookie
      name: echo_session

  schemas:
    PermissionCheckRequest:
      type: object
      required:
        - permission
      properties:
        permission:
          $ref: '#/components/schemas/Permission'
        branchId:
          type: string
          format: uuid
          description: Branch context for permission check

    PermissionCheckResponse:
      type: object
      required:
        - granted
        - permission
      properties:
        granted:
          type: boolean
        permission:
          $ref: '#/components/schemas/Permission'
        reason:
          type: string
          description: Explanation if denied

    UserPermissions:
      type: object
      required:
        - userId
        - roles
        - permissions
      properties:
        userId:
          type: string
          format: uuid
        roles:
          type: array
          items:
            $ref: '#/components/schemas/Role'
        permissions:
          type: array
          items:
            $ref: '#/components/schemas/Permission'

    BranchPermissions:
      type: object
      required:
        - branchId
        - canView
        - canEdit
        - canSubmitForReview
        - canReview
        - canApprove
        - canPublish
        - canArchive
        - canManageCollaborators
        - canManageReviewers
      properties:
        branchId:
          type: string
          format: uuid
        canView:
          type: boolean
        canEdit:
          type: boolean
        canSubmitForReview:
          type: boolean
        canReview:
          type: boolean
        canApprove:
          type: boolean
        canPublish:
          type: boolean
        canArchive:
          type: boolean
        canManageCollaborators:
          type: boolean
        canManageReviewers:
          type: boolean
        isOwner:
          type: boolean
        isCollaborator:
          type: boolean
        isAssignedReviewer:
          type: boolean

    CollaboratorSummary:
      type: object
      required:
        - userId
        - email
        - displayName
        - addedAt
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        displayName:
          type: string
        avatarUrl:
          type: string
          format: uri
        addedAt:
          type: string
          format: date-time
        addedBy:
          type: string
          format: uuid

    ReviewerSummary:
      type: object
      required:
        - userId
        - email
        - displayName
        - assignedAt
        - status
      properties:
        userId:
          type: string
          format: uuid
        email:
          type: string
          format: email
        displayName:
          type: string
        avatarUrl:
          type: string
          format: uri
        assignedAt:
          type: string
          format: date-time
        status:
          type: string
          enum: [pending, approved, changes_requested]
        reviewedAt:
          type: string
          format: date-time

    Permission:
      type: string
      enum:
        - branch.create
        - branch.view
        - branch.edit
        - branch.delete
        - branch.submit_for_review
        - branch.archive
        - review.view
        - review.approve
        - review.request_changes
        - publish.execute
        - user.view
        - user.manage_roles
        - audit.view

    Role:
      type: string
      enum:
        - contributor
        - reviewer
        - administrator

    PermissionDeniedError:
      type: object
      required:
        - error
        - message
        - requiredPermission
        - guidance
      properties:
        error:
          type: string
          enum: [permission_denied]
        message:
          type: string
        requiredPermission:
          $ref: '#/components/schemas/Permission'
        currentRole:
          $ref: '#/components/schemas/Role'
        guidance:
          type: string
          description: Actionable next steps for the user
